### ISSUE TITLE
WebView on Android Crashes Randomly

### ISSUE THREAD

**Issue by ammarahm-ed** [react-native-webview/react-native-webview#1838]
WebView on Android crashes sometimes in a strange way. The app keeps working normally however the WebView is not loaded and onError does not get called. Is there a way to handle this and reload the WebView.

**To Reproduce:**
I haven't found a way to reproduce the issue since it happens very randomly but is annoying because you have to restart the app.

**Expected behavior:**
The WebView should keep running normally.

**Screenshots/Videos:**
Here is the crashlog. `onError` is not fired either.
```
01-07 18:08:56.840 25270 25270 W cr_AwContents: Application attempted to call on a destroyed WebView
01-07 18:08:56.840 25270 25270 W cr_AwContents: java.lang.Throwable
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-428010133:2)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at org.chromium.android_webview.AwContents.h(chromium-TrichromeWebViewGoogle.aab-stable-428010133:1)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(chromium-TrichromeWebViewGoogle.aab-stable-428010133:8)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.webkit.WebView.evaluateJavascript(WebView.java:911)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager$f.a(Unknown Source:7)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager.receiveCommand(Unknown Source:114)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager.receiveCommand(Unknown Source:2)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(Unknown Source:18)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(Unknown Source:12)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(Unknown Source:140)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(Unknown Source:53)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(Unknown Source:0)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(Unknown Source:31)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(Unknown Source:0)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(Unknown Source:46)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(Unknown Source:2)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.view.Choreographer.doCallbacks(Choreographer.java:875)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.view.Choreographer.doFrame(Choreographer.java:772)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.os.Handler.handleCallback(Handler.java:900)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.os.Handler.dispatchMessage(Handler.java:103)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.os.Looper.loop(Looper.java:219)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at android.app.ActivityThread.main(ActivityThread.java:8347)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at java.lang.reflect.Method.invoke(Native Method)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-07 18:08:56.840 25270 25270 W cr_AwContents:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
01-07 18:08:56.842 25270 25270 I chatty  : uid=10312(com.streetwriters.notesnook) identical 3 lines
01-07 18:08:56.854 25270 25270 W cr_AwContents: Application attempted to call on a destroyed WebView
01-07 18:08:56.854 25270 25270 W cr_AwContents: java.lang.Throwable
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-428010133:2)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at org.chromium.android_webview.AwContents.h(chromium-TrichromeWebViewGoogle.aab-stable-428010133:1)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(chromium-TrichromeWebViewGoogle.aab-stable-428010133:8)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.webkit.WebView.evaluateJavascript(WebView.java:911)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager$f.a(Unknown Source:7)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager.receiveCommand(Unknown Source:114)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager.receiveCommand(Unknown Source:2)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(Unknown Source:18)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(Unknown Source:12)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(Unknown Source:140)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(Unknown Source:53)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(Unknown Source:0)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(Unknown Source:31)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(Unknown Source:0)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(Unknown Source:46)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(Unknown Source:2)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.view.Choreographer.doCallbacks(Choreographer.java:875)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.view.Choreographer.doFrame(Choreographer.java:772)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.os.Handler.handleCallback(Handler.java:900)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.os.Handler.dispatchMessage(Handler.java:103)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.os.Looper.loop(Looper.java:219)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at android.app.ActivityThread.main(ActivityThread.java:8347)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at java.lang.reflect.Method.invoke(Native Method)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-07 18:08:56.854 25270 25270 W cr_AwContents:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
01-07 18:08:56.855  1275  8936 E InputDispatcher: Window handle recents_animation_input_consumer has no registered input channel
01-07 18:08:56.855  1275  8936 I chatty  : uid=1000(system) Binder:1275_1B identical 2 lines
01-07 18:08:56.855  1275  8936 E InputDispatcher: Window handle recents_animation_input_consumer has no registered input channel
01-07 18:08:56.888 25270 25270 W cr_AwContents: Application attempted to call on a destroyed WebView
01-07 18:08:56.888 25270 25270 W cr_AwContents: java.lang.Throwable
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at org.chromium.android_webview.AwContents.p(chromium-TrichromeWebViewGoogle.aab-stable-428010133:2)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at org.chromium.android_webview.AwContents.h(chromium-TrichromeWebViewGoogle.aab-stable-428010133:1)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(chromium-TrichromeWebViewGoogle.aab-stable-428010133:8)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.webkit.WebView.evaluateJavascript(WebView.java:911)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager$f.a(Unknown Source:7)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager.receiveCommand(Unknown Source:114)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.reactnativecommunity.webview.RNCWebViewManager.receiveCommand(Unknown Source:2)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(Unknown Source:18)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(Unknown Source:12)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(Unknown Source:140)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(Unknown Source:53)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(Unknown Source:0)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(Unknown Source:31)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(Unknown Source:0)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(Unknown Source:46)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(Unknown Source:2)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.view.Choreographer.doCallbacks(Choreographer.java:875)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.view.Choreographer.doFrame(Choreographer.java:772)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.os.Handler.handleCallback(Handler.java:900)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.os.Handler.dispatchMessage(Handler.java:103)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.os.Looper.loop(Looper.java:219)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at android.app.ActivityThread.main(ActivityThread.java:8347)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at java.lang.reflect.Method.invoke(Native Method)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-07 18:08:56.888 25270 25270 W cr_AwContents:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Environment:**
 - OS: Android
 - OS version: All versions
 - react-native version: 0.63.4
 - react-native-webview version: v11.0.2

**Comment by lcaccavaro** [comment]
I'm facing the same problem.
Is there any updated?

I'm already in the last version 11.2.3

**Comment by ammarahm-ed** [comment]
@lcaccavaro I think I fixed it by handling the `onRenderProcessGone` event and removing and adding back the `WebView` again through state.

```jsx
const [loaded,setLoaded] = useState(true);

/// in WebView
return loaded && <WebView
onRenderProcessGone={() => {
setLoaded(false);
setTimeout(()=> setLoaded(true),100)
}}
/>
...
```

**Comment by lcaccavaro** [comment]
@ammarahm-ed ,

Thanks for your trying.. 
But the problem persists..
Sometimes, when I try to open a webview and back to native and open webview,  the app cashes and close.

**Comment by ammarahm-ed** [comment]
@lcaccavaro then your problem is different than mine because for me that app never crashed, only the WebView. Maybe run `adb logcat` and post what you find in the logs when the app crashes

**Comment by lcaccavaro** [comment]
Please let me know if you can find something that can help.


`--------- beginning of main
02-19 16:55:48.342  1779  9114 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:55:48.539  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:48.539  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:48.640  1786  3564 W audio_hw_generic: Not supplying enough data to HAL, expected position 3403505 , only wrote 3403489
02-19 16:55:48.725  3563  9115 E memtrack: Couldn't load memtrack module
02-19 16:55:48.725  3563  9115 W android.os.Debug: failed to get memory consumption info: -1
02-19 16:55:49.542  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:49.542  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:50.351  1779  9116 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:55:50.548  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:50.548  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:51.552  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:51.552  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:51.774  1786  1986 W audio_hw_generic: Not supplying enough data to HAL, expected position 3678082 , only wrote 3541638
02-19 16:55:52.370  1779  9119 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:55:52.556  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:52.556  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:53.558  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:53.558  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:54.385  1779  9125 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:55:54.560  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:54.560  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:55.561  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:55.561  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:56.392  1779  9126 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:55:56.567  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:56.567  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:57.244  2031  4639 D WificondControl: Scan result ready event
02-19 16:55:57.570  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:57.570  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:58.400  1779  9136 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:55:58.574  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:58.574  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:55:59.577  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:55:59.577  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:56:00.022  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:00.410  1779  9137 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:56:00.579  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:56:00.579  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:56:01.298  1786  3564 W audio_hw_generic: Not supplying enough data to HAL, expected position 3541655 , only wrote 3541638
02-19 16:56:01.584  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:56:01.584  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:56:01.651  8742  9141 W cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
02-19 16:56:01.655  8742  9141 W com.p1p3_mobil: Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (greylist, reflection, allowed)
02-19 16:56:01.666  8742  8742 I cr_BrowserStartup: Initializing chromium process, singleProcess=false
02-19 16:56:01.681  2290  2290 D Zygote  : Forked child process 9143
--------- beginning of system
02-19 16:56:01.691  2031  2059 I ActivityManager: Start proc 9143:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0/u0i4 for  {com.p1p3_mobile/org.chromium.content.app.SandboxedProcessService0}
02-19 16:56:01.693  9143  9143 W ProcessService: Unexpected CPU variant for X86 using defaults: x86
02-19 16:56:01.704  9143  9143 E ProcessService: Not starting debugger since process cannot load the jdwp agent.
02-19 16:56:01.738  9143  9143 I LoadedApk: No resource references to update in package com.google.android.webview
02-19 16:56:01.738  9143  9143 I LoadedApk: No resource references to update in package com.google.android.trichromelibrary
02-19 16:56:01.741  9143  9143 I cr_ChildProcessService: Creating new ChildProcessService pid=9143
02-19 16:56:01.813  2031  4639 D ConnectivityService: requestNetwork for uid/pid:10134/8742 NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ]
02-19 16:56:01.815  2333  2333 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] with score 60 and serial -1
02-19 16:56:01.815  2031  2130 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] with score 60 and serial -1
02-19 16:56:01.815  2031  2130 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] with score 60 and serial -1
02-19 16:56:01.828  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
02-19 16:56:01.829  8742  8742 W com.p1p3_mobil: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
02-19 16:56:01.863  8742  9168 W cr_media: Requires BLUETOOTH permission
02-19 16:56:01.870  8742  9175 D HostConnection: HostConnection::get() New Host Connection established 0xbf7a3a90, tid 9175
02-19 16:56:01.872  8742  9175 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
02-19 16:56:01.876  8742  9175 D eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
02-19 16:56:01.876  8742  9175 D EGL_emulation: eglCreateContext: 0xbfc47840: maj 3 min 0 rcv 3
02-19 16:56:01.876  8742  9175 D EGL_emulation: eglMakeCurrent: 0xbfc47840: ver 3 0 (tinfo 0xbfca5350)
02-19 16:56:01.876  9143  9167 I cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 4337-4338)
02-19 16:56:01.878  9143  9167 I chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
02-19 16:56:01.878  9143  9167 I cr_LibraryLoader: Expected native library version number "74.0.3729.185", actual native library version number "74.0.3729.185"
02-19 16:56:01.909  2031  2806 D ConnectivityService: requestNetwork for uid/pid:10134/8742 NetworkRequest [ TRACK_DEFAULT id=48, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ]
02-19 16:56:01.911  2031  2130 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=48, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] with score 60 and serial -1
02-19 16:56:01.911  2031  2130 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=48, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] with score 60 and serial -1
02-19 16:56:01.911  2333  2333 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=48, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] with score 60 and serial -1
02-19 16:56:01.969  8742  9175 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
02-19 16:56:01.977  8742  9175 W cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
02-19 16:56:01.993  8742  9175 D eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
02-19 16:56:01.993  8742  9175 D EGL_emulation: eglCreateContext: 0xbf683b40: maj 3 min 0 rcv 3
02-19 16:56:01.993  8742  9175 D EGL_emulation: eglMakeCurrent: 0xbf683b40: ver 3 0 (tinfo 0xbfca5350)
02-19 16:56:02.020  8742  9175 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
02-19 16:56:02.020  8742  9175 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
02-19 16:56:02.029  8742  9175 D eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 0 0
02-19 16:56:02.082  8742  9175 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
02-19 16:56:02.082  8742  9175 E eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
02-19 16:56:02.086  8742  9175 D eglCodecCommon: setVertexArrayObject: set vao to 2 (2) 0 0
--------- beginning of crash
02-19 16:56:02.143  8742  8792 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c in tid 8792 (RenderThread), pid 8742 (com.p1p3_mobile)
02-19 16:56:02.202  9191  9191 E DEBUG   : failed to readlink /proc/8792/fd/157: No such file or directory
02-19 16:56:02.202  9191  9191 E DEBUG   : failed to readlink /proc/8792/fd/158: No such file or directory
02-19 16:56:02.242  9191  9191 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-19 16:56:02.247  1863  1863 I /system/bin/tombstoned: received crash request for pid 8792
02-19 16:56:02.248  9191  9191 I crash_dump32: performing dump of process 8742 (target tid = 8792)
02-19 16:56:02.262  9191  9191 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-19 16:56:02.262  9191  9191 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
02-19 16:56:02.262  9191  9191 F DEBUG   : Revision: '0'
02-19 16:56:02.262  9191  9191 F DEBUG   : ABI: 'x86'
02-19 16:56:02.263  9191  9191 F DEBUG   : Timestamp: 2021-02-19 16:56:02-0300
02-19 16:56:02.263  9191  9191 F DEBUG   : pid: 8742, tid: 8792, name: RenderThread  >>> com.p1p3_mobile <<<
02-19 16:56:02.263  9191  9191 F DEBUG   : uid: 10134
02-19 16:56:02.263  9191  9191 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c
02-19 16:56:02.263  9191  9191 F DEBUG   : Cause: null pointer dereference
02-19 16:56:02.263  9191  9191 F DEBUG   :     eax 00000000  ebx eae759ac  ecx eae6d548  edx ed976460
02-19 16:56:02.263  9191  9191 F DEBUG   :     edi c05e5bc0  esi 00000000
02-19 16:56:02.263  9191  9191 F DEBUG   :     ebp c05e5ab8  esp c05e5aa0  eip ea9789ba
02-19 16:56:02.313  9191  9191 F DEBUG   : 
02-19 16:56:02.313  9191  9191 F DEBUG   : backtrace:
02-19 16:56:02.313  9191  9191 F DEBUG   :       #00 pc 002ad9ba  /system/lib/libhwui.so (SkSurface::getCanvas()+26) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #01 pc 0037cd4f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+2191) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #02 pc 003f4c34  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+612) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #03 pc 00379552  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+306) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #04 pc 0062770a  /system/lib/libhwui.so (android::uirenderer::$_22::__invoke(void const*, SkCanvas*, SkMatrix const&)+42) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #05 pc 001f8f90  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2080) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #06 pc 003f4b8d  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+445) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #07 pc 00379552  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+306) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #08 pc 0062770a  /system/lib/libhwui.so (android::uirenderer::$_22::__invoke(void const*, SkCanvas*, SkMatrix const&)+42) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #09 pc 001f8f90  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2080) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #10 pc 003f4b8d  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+445) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #11 pc 00379552  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+306) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #12 pc 0062770a  /system/lib/libhwui.so (android::uirenderer::$_22::__invoke(void const*, SkCanvas*, SkMatrix const&)+42) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #13 pc 001f8f90  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2080) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #14 pc 003f4b8d  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+445) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #15 pc 00379552  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+306) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #16 pc 0062770a  /system/lib/libhwui.so (android::uirenderer::$_22::__invoke(void const*, SkCanvas*, SkMatrix const&)+42) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #17 pc 001f8f90  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2080) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #18 pc 003f4b8d  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+445) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #19 pc 00379552  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+306) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #20 pc 0062770a  /system/lib/libhwui.so (android::uirenderer::$_22::__invoke(void const*, SkCanvas*, SkMatrix const&)+42) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #21 pc 001f8f90  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2080) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #22 pc 002584d2  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+258) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #23 pc 002b02c2  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool)+626) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #24 pc 002ad40d  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+93) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #25 pc 002ad0b0  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, android::uirenderer::FrameInfoVisualizer*)+352) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #26 pc 002ba04c  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+332) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #27 pc 002b9098  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+296) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #28 pc 002cf38f  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+255) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #29 pc 002cf0ff  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+127) (BuildId: 57c0bd14db56e9b741ef49031022974d)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #30 pc 00014166  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+342) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #31 pc 00013aa6  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+246) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #32 pc 0011a8e5  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+53) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
02-19 16:56:02.313  9191  9191 F DEBUG   :       #33 pc 000af6a7  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
02-19 16:56:02.363  8742  8755 I com.p1p3_mobil: NativeAlloc concurrent copying GC freed 63589(2515KB) AllocSpace objects, 2(40KB) LOS objects, 49% free, 4651KB/9303KB, paused 69us total 218.316ms
02-19 16:56:02.425  1779  9202 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-19 16:56:02.584  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:56:02.584  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:56:02.725  1863  1863 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_07
02-19 16:56:02.728  2031  2064 I BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
02-19 16:56:02.729  2031  2064 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
02-19 16:56:02.730  2031  9203 W ActivityTaskManager:   Force finishing activity com.p1p3_mobile/.MainActivity
02-19 16:56:02.730  2031  9204 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
02-19 16:56:02.732  2031  9203 W InputReader: Device has associated, but no associated display id.
02-19 16:56:02.741  2031  2058 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-19 16:56:02.742  2031  2058 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 16:56:02.747  2031  2058 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-19 16:56:02.747  2031  2058 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-19 16:56:02.733  2031  9203 I chatty  : uid=1000 system_server identical 8 lines
02-19 16:56:02.733  2031  9203 W InputReader: Device has associated, but no associated display id.
02-19 16:56:02.816  2031  2121 W InputDispatcher: channel '820ec5a com.p1p3_mobile/com.p1p3_mobile.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-19 16:56:02.817  2031  2121 E InputDispatcher: channel '820ec5a com.p1p3_mobile/com.p1p3_mobile.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-19 16:56:02.818  2031  7356 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=48, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ], android.os.BinderProxy@ede1ef0)
02-19 16:56:02.820  2031  2133 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=48, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] (release request)
02-19 16:56:02.821  2031  7263 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=49, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10134] ], android.os.BinderProxy@fa07c69)
02-19 16:56:02.822  2031  7356 I WindowManager: WIN DEATH: Window{820ec5a u0 com.p1p3_mobile/com.p1p3_mobile.MainActivity}
02-19 16:56:02.822  2031  7356 W InputDispatcher: Attempted to unregister already unregistered input channel '820ec5a com.p1p3_mobile/com.p1p3_mobile.MainActivity (server)'
02-19 16:56:02.822  1780  1780 I Zygote  : Process 8742 exited due to signal 11 (Segmentation fault)
02-19 16:56:02.822  2031  2328 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ], android.os.BinderProxy@f7326ee)
02-19 16:56:02.823  2031  2133 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10134] ] (release request)
02-19 16:56:02.823  2031  2795 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=47, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10134] ], android.os.BinderProxy@3f8478f)
02-19 16:56:02.824  2031  7832 I ActivityManager: Process com.p1p3_mobile (pid 8742) has died: vis+99 TOP 
02-19 16:56:02.825  2031  2060 I libprocessgroup: Successfully killed process cgroup uid 10134 pid 8742 in 0ms
02-19 16:56:02.830  2031  7832 W InputReader: Device has associated, but no associated display id.
02-19 16:56:02.835  2031  7832 I ActivityManager: Killing 9143:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0/u0a134i4 (adj 0): isolated not needed
02-19 16:56:02.833  2031  7832 I chatty  : uid=1000(system) Binder:2031_20 identical 18 lines
02-19 16:56:02.833  2031  7832 W InputReader: Device has associated, but no associated display id.
02-19 16:56:02.835  2031  2060 I libprocessgroup: Successfully killed process cgroup uid 99004 pid 9143 in 0ms
02-19 16:56:02.838  2031  2052 W ActivityManager: setHasOverlayUi called on unknown pid: 8742
02-19 16:56:02.843  2031  2031 W ActivityManager: Unable to start service Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } U=0: not found
02-19 16:56:02.843  2031  2031 W RemoteAppPredictionService: could not bind to Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } using flags 67108865
02-19 16:56:02.843  2290  2290 I Zygote  : Process 9143 exited cleanly (0)
02-19 16:56:02.851  1798  1942 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-19 16:56:02.853  1798  1798 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-19 16:56:02.878  1798  1942 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-19 16:56:02.878  1798  1798 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-19 16:56:02.884  2398  2847 D EGL_emulation: eglMakeCurrent: 0xda61a300: ver 3 0 (tinfo 0xda60f830)
02-19 16:56:02.885  1798  1879 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-19 16:56:02.893  3901  3991 D EGL_emulation: eglMakeCurrent: 0xe27e7e60: ver 3 0 (tinfo 0xd71c1ae0)
02-19 16:56:02.903  1798  1798 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-19 16:56:02.928  3901  3901 W ThreadPoolDumper: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
02-19 16:56:02.941  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:02.945  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:02.947  3901  4023 W SessionLifecycleManager: Handover failed. Creating new session controller.
02-19 16:56:02.951  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:02.986  2167  2450 I chatty  : uid=10104(com.android.systemui) RenderThread identical 4 lines
02-19 16:56:02.988  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:02.995  3901  4031 W LocationOracle: No location history returned by ContextManager
02-19 16:56:02.999  2557  2557 D BoundBrokerSvc: onBind: Intent { act=com.google.android.contextmanager.service.ContextManagerService.START pkg=com.google.android.gms }
02-19 16:56:02.999  2557  2557 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.contextmanager.service.ContextManagerService.START pkg=com.google.android.gms }
02-19 16:56:03.003  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.005  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.015  3901  4023 I MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
02-19 16:56:03.017  3901  4023 W ErrorReporter: reportError [type: 211, code: 393244, bug: 0]: errorCode: 393244, engine: 0
02-19 16:56:03.017  3901  4023 I MicroDetector: Keeping mic open: false
02-19 16:56:03.017  3901  4023 I MicroDetectionWorker: #onError(false)
02-19 16:56:03.018  3901  4031 I DeviceStateChecker: DeviceStateChecker cancelled
02-19 16:56:03.023  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.026  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.036  2557  7836 W ctxmgr  : [AclManager] No 3 for (accnt=account#-517948760#, com.google.android.gms(10098):UserVelocityProducer, vrsn=210214040, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2557 ,  featureId = null). Was: 3 for 1, account#-517948760# [CONTEXT service_id=47 ]
02-19 16:56:03.039  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.043  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: exception when setting module id
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@210214040@21.02.14 (120700-352619232):2)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at ages.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):4)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at agev.aa(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at agbe.a(Unknown Source:3)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sjj.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sfo.f(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sfm.e(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sig.p(:com.google.android.gms@210214040@21.02.14 (120700-352619232):2)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sig.v(:com.google.android.gms@210214040@21.02.14 (120700-352619232):3)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sig.d(:com.google.android.gms@210214040@21.02.14 (120700-352619232):2)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sig.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):7)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sig.m(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at syr.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sxs.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):8)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sxj.d(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at sxm.handleMessage(:com.google.android.gms@210214040@21.02.14 (120700-352619232):23)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at afty.iE(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at afty.dispatchMessage(:com.google.android.gms@210214040@21.02.14 (120700-352619232):10)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at android.os.Looper.loop(Looper.java:214)
02-19 16:56:03.045  2557  2600 E ModuleIdSetter: 	at android.os.HandlerThread.run(HandlerThread.java:67)
02-19 16:56:03.045  2557  2557 D BoundBrokerSvc: onBind: Intent { act=com.google.android.contextmanager.service.ContextManagerService.START cmp=com.google.android.gms/.chimera.PersistentApiService }
02-19 16:56:03.045  2557  2557 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.contextmanager.service.ContextManagerService.START cmp=com.google.android.gms/.chimera.PersistentApiService }
02-19 16:56:03.055  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.055  2557  7835 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.059  2167  2450 D EGL_emulation: eglMakeCurrent: 0xda61a780: ver 3 0 (tinfo 0xda60fd00)
02-19 16:56:03.071  2557  9213 I LogUtils: [Places]: ?: PlacesBleScanner stop() disabled [CONTEXT service_id=253 ]
02-19 16:56:03.078  2557  9213 I LogUtils: [Places]: ?: PlacesBleScanner stop() disabled [CONTEXT service_id=253 ]
02-19 16:56:03.079  2557  9213 I PlacesLogger: [PlaceInferenceEngine]: [anon] Changed inference mode: 0 [CONTEXT service_id=253 ]
02-19 16:56:03.079  2557  6845 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.081  2557  7836 I ctxmgr  : [ProducerStatusImpl] updateStateForNewContextData: inactive, contextName=7 [CONTEXT service_id=47 ]
02-19 16:56:03.084  2557  9214 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.095  2031  7832 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764543347 duration=-1
02-19 16:56:03.097  2031  7832 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764563095 duration=0
02-19 16:56:03.115  2031  7832 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764563097 duration=0
02-19 16:56:03.101  2557  9214 I chatty  : uid=10098(com.google.android.gms) lowpool[22] identical 1 line
02-19 16:56:03.107  2557  9214 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.115  2557  6845 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.118  2031  2591 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764563115 duration=0
02-19 16:56:03.124  2557  9213 I LogUtils: [Places]: ?: PlacesBleScanner stop() disabled [CONTEXT service_id=253 ]
02-19 16:56:03.130  2557  9213 I LogUtils: [Places]: ?: PlacesBleScanner start() with priority 2 disabled [CONTEXT service_id=253 ]
02-19 16:56:03.131  2557  9213 I PlacesLogger: [PlaceInferenceEngine]: [anon] Changed inference mode: 1 [CONTEXT service_id=253 ]
02-19 16:56:03.134  2557  9213 I Places  : Converted 0 out of 1 WiFi scans
02-19 16:56:03.139  2031  2591 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764563118 duration=0
02-19 16:56:03.142  2031  2591 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764563139 duration=0
02-19 16:56:03.145  2031  2591 W AppOps  : Noting op not finished: uid 10098 pkg com.google.android.gms code 79 time=1613764563142 duration=0
02-19 16:56:03.145  2557  7836 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.146  2557  6845 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.146  2557  9213 I PlacesLogger: [PlaceInferenceEngine]: [anon] Changed inference mode: 1 [CONTEXT service_id=253 ]
02-19 16:56:03.147  2557  9214 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.157  2557  7835 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.158  2557  9214 I PlacesLogger: [PlaceInferenceEngine]: No beacon scan available - ignoring candidates. [CONTEXT service_id=253 ]
02-19 16:56:03.171  2557  9214 I LogUtils: [Places]: ?: Couldn't find platform key file. [CONTEXT service_id=253 ]
02-19 16:56:03.233  2031  2052 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{4998b95 u0 com.p1p3_mobile/.MainActivity t-1 f}
02-19 16:56:03.590  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:56:03.590  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
02-19 16:56:04.432  1786  1986 W audio_hw_generic: Not supplying enough data to HAL, expected position 3816166 , only wrote 3679787
02-19 16:56:04.593  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
02-19 16:56:04.593  1797  2250 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8`

**Comment by ammarahm-ed** [comment]
@lcaccavaro The log you posted does not include a single line related to react native application. where did you get it from and how?

**Comment by lcaccavaro** [comment]
I opened the app and before I got the error I started adb logcat
then I stopped and paste here.
There is some points related to webview but I could not understand anything.
I don't know if I did something wrong.

**Comment by lcaccavaro** [comment]
Hi @ammarahm-ed ,

I just tried to run adb logcat filtering by ReactNative as you mentioned with the following command.
adb logcat *:S ReactNative:V ReactNativeJS:V
But I noticed that nothing was returned, but I could noticed that the crash happens after the line.
--------- beginning of crash
So I run again without filter, and I got this issue.

> 02-26 11:03:52.909 17741 17788 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c in tid 17788 (RenderThread), pid 17741 (com.p1p3_mobile)
02-26 11:03:52.911  1779 18117 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
02-26 11:03:52.985 18119 18119 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-26 11:03:52.986  1863  1863 I /system/bin/tombstoned: received crash request for pid 17788
02-26 11:03:52.991 18119 18119 I crash_dump32: performing dump of process 17741 (target tid = 17788)
02-26 11:03:53.000 18119 18119 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-26 11:03:53.000 18119 18119 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
02-26 11:03:53.000 18119 18119 F DEBUG   : Revision: '0'
02-26 11:03:53.000 18119 18119 F DEBUG   : ABI: 'x86'
02-26 11:03:53.000 18119 18119 F DEBUG   : Timestamp: 2021-02-26 11:03:52-0300
02-26 11:03:53.000 18119 18119 F DEBUG   : pid: 17741, tid: 17788, name: RenderThread  >>> com.p1p3_mobile <<<
02-26 11:03:53.000 18119 18119 F DEBUG   : uid: 10138
02-26 11:03:53.000 18119 18119 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c
02-26 11:03:53.000 18119 18119 F DEBUG   : Cause: null pointer dereference
02-26 11:03:53.000 18119 18119 F DEBUG   :     eax 00000000  ebx f216e9ac  ecx f2166548  edx f5e76460
02-26 11:03:53.000 18119 18119 F DEBUG   :     edi c8133bc0  esi 00000000
02-26 11:03:53.000 18119 18119 F DEBUG   :     ebp c8133ab8  esp c8133aa0  eip f1c719ba

Did you see any problem with this SIGSEGV?

Thanks for your help

**Comment by lcaccavaro** [comment]
@ammarahm-ed ,

One update, I could fix disabling the following property in android manifest.
android:hardwareAccelerated="false"

I'm a little bit warning about that.
Which impact could I have with that?

Thanks.

**Comment by lcaccavaro** [comment]
A new update..

I found that there is androidHardwareAccelerationDisabled prop in webview that resolved my problem and does not impact the rest of application.

**Comment by rdgoutiyama** [comment]
Here,  when I have vimeo or youtube video embedded, using androidHardwareAccelerationDisabled={false} crashes sometimes with android 10.

Using androidHardwareAccelerationDisabled={true} not crashes, but vimeo or youtube video not show image, only audio. 

My react-native-webview version is 11.2.3

**Comment by ggittt** [comment]
maby https://github.com/react-native-webview/react-native-webview/issues/1915#issuecomment-808869253

**Comment by bemaverick** [comment]
androidHardwareAccelerationDisabled={true} 
works for me

**Comment by JairajJangleSLIOT** [comment]
Setting `androidHardwareAccelerationDisabled={true}` does not work for me. This crash only occurs on certain devices for my app. For example, the app works fine on Xiaomi and Moto phones but the app crashes on Samsung Galaxy S10 phone.

**Comment by linonetwo** [comment]
Where is androidHardwareAccelerationDisabled ? Seems it is not exist. Maybe renamed to `renderToHardwareTextureAndroid`

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/197dee6e-11d3-4cc2-aaab-62aa6ec9d001" />

**Comment by Nevokar** [comment]
> Where is androidHardwareAccelerationDisabled ? Seems it is not exist. Maybe renamed to `renderToHardwareTextureAndroid`
> <img alt="Image" width="959" src="https://private-user-images.githubusercontent.com/3746270/408840854-197dee6e-11d3-4cc2-aaab-62aa6ec9d001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3NjgzMTUsIm5iZiI6MTczODc2ODAxNSwicGF0aCI6Ii8zNzQ2MjcwLzQwODg0MDg1NC0xOTdkZWU2ZS0xMWQzLTRjYzItYWFhYi02MmFhNmVjOWQwMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMDVUMTUwNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY5YzczNjNmNDE3ZTE5ZmJkNjlkNTA5YmU4MzRiY2UxZWVmNTA1MDFhNTFkMDNhOWMyMDdhNzU5ZWRjMDljZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ruaXlWdy4LhuweJEFzO06nTkrw-4WbBwyphByEiPZm0">

well, seeing [this comit](https://github.com/search?q=repo%3Areact-native-webview%2Freact-native-webview+androidHardwareAccelerationDisabled&type=commits) ,it seems to have been changed with androidLayerType , but setting it to 'software' makes things a bit laggy
