### ISSUE TITLE
ios 16, bounces={false} not working

### ISSUE THREAD

**Issue by baesumin** [react-native-webview/react-native-webview#2654]
when using ios 16 beta, bounces={false} doesn't work..

**Environment:**
 - OS: ios
 - OS version: 16 beta
 - react-native version: 0.66
 - react-native-webview version: 11.14.4

**Comment by baesumin** [comment]
https://developer.apple.com/forums/thread/711601

**Comment by Jim-Bar** [comment]
Same problem here, do someone knows how the workaround in the linked bug above can be applied in React Native?

**Comment by mgscreativa** [comment]
Same here, bounces set to false but the webview "bounces" anyway

https://user-images.githubusercontent.com/1286632/205701018-1f91f827-b72f-47a7-bb85-33d30e25924c.MP4

**Comment by Jim-Bar** [comment]
Hi, this issue seems to have been resolved by Apple, see #2692. We do not seem to reproduce it in our app.

**Comment by squio** [comment]
Same here, issue seams to be resolved, please verify and close

**Comment by albert17** [comment]
@Jim-Bar @squio Really? I am still facing this issue.
- react-native: 0.69.3
- react-native-webview: 11.2.4

**Comment by squio** [comment]
@albert17 not sure about your case but for RN > 0.70 and RN Webview > 12 it seems to be fixed, maybe you can try to upgrade?

**Comment by albert17** [comment]
@squio Updated to RN 0.71.7 and RNWebview 11.26.1 and still failing.

I will upgrade to RN Webview > 12 when there is a solution for testing. I tried and it broke my Jest testing.

**Comment by nati673** [comment]
overScrollMode="never"
