### ISSUE TITLE
Webview displays blank after going to background

### ISSUE THREAD

**Issue by melihozlem** [react-native-webview/react-native-webview#3062]
When app loads for the first time, the webview works fine. If it goes in the background after some time, bringing the app back to the foreground shows nothing. What needs to be done to allow the webview to load again after it goes back to the foreground? Using react native

**Comment by o-alexandrov** [comment]
I experienced the same issue, will try to resolve this by wrapping Webview in a React Error Boundary to log the exact error and trigger an update in a `key`, so Webview component instance would be new.

My worry is Webview could be silently failing outside of ReactNative and the Error Boundary wouldn’t catch the error in this case, but will report in a few days with findings

**Comment by o-alexandrov** [comment]
Using [onContentProcessDidTerminate](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#oncontentprocessdidterminate) resolved an issue for me.
What about you @melihozlem ?

**Comment by melihozlem** [comment]
It still happens

**Comment by melihozlem** [comment]
This is the code
```
    const webViewRef = useRef()
    return (
    <WebView
      source={{ uri: 'http://' }}
      onContentProcessDidTerminate={() => webViewRef.current.reload()}
      ref={webViewRef}
      style={{ marginTop: 20 }}
    />
    )
```

**Comment by o-alexandrov** [comment]
@melihozlem what version of react-native-webview are you using? I can’t reproduce your issue using the latest one. Your issue might be related to [this PR](https://github.com/react-native-webview/react-native-webview/pull/3041) that was recently merged

**Comment by melihozlem** [comment]
Using 13.3.0 in packge.json. Is there a cli command to check?

**Comment by o-alexandrov** [comment]
@melihozlem you could check in your lock file, depending on the package manager:
- yarn.lock
- package-lock.json
- etc.

13.3.0 is the latest and `it's unlikely` you didn't reinstall packages the last time you updated the version in `package.json`.
So I think the simplest way to understand your issue would be for you to create a minimal reproducible example of how you use it.

**Comment by melihozlem** [comment]
What I pasted is the entire app. There is nothing else. If the app goes to background, if other apps are used, after some time, coming back shows white screen

**Comment by antonbavykin1991** [comment]
Have similar issue.
"react-native-webview": "11.23.0",

**Comment by Stephen-Song** [comment]
same case happen to me in android @TheAlmightyBob

**Comment by TheAlmightyBob** [comment]
What platform is this on?

**Comment by linonetwo** [comment]
I'm on Android. After go background for 5-10min, this will happen.
![截屏2023-09-08 12 57 40](https://github.com/react-native-webview/react-native-webview/assets/3746270/3d6814cb-3f59-4102-ad45-94621cc5c5f4)

**Comment by linonetwo** [comment]
I think for Android, we should use [onRenderProcessGone](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onRenderProcessGone)

`nativeEvent.didCrash` will be false if this is just a normal technical adjustment that Android OS recycle the webview.
You can reproduce this even on development, just move expo to the background, then, Genshin, start! After a while you go back, will found the warning ` WARN  WebView Crashed: false`

Anyway, we can try reload the webview.

`webViewReference.current?.reload?.();` will not work.

``ts
  const [autoIncrementingNumber, setAutoIncrementingNumber] = useState(0);
  return (
    <WebView
      key={autoIncrementingNumber}
      onRenderProcessGone={syntheticEvent => {
        const { nativeEvent } = syntheticEvent;
        console.warn(
          'WebView Crashed:',
          nativeEvent.didCrash,
        );
        // webViewReference.current?.reload?.();
        setAutoIncrementingNumber(autoIncrementingNumber + 1);
      }}
```

seem to work.

**Comment by builtbylane** [comment]
We're seeing this issue when app goes into background for iOS and Android.

**Comment by TheAlmightyBob** [comment]
@melnikovkolya Do you know that your users are hitting `onContentProcessDidTerminate`? (do they see the alert from `alertGeneralError()` or are you collecting telemetry on this?)

**Comment by andreaslimidev** [comment]
We also struggle with this issue. After the app has been active OR inactive for a while, the webview suddenly goes blank. The issue can be reproduced by opening a bunch of other apps (preferably 5-10 large games). When the app is then opened again, `onContentProcessDidTerminate` fires and the webview goes blank.

This is a critical issue for us, as we would like to avoid refreshing the app to preserve the user state in the webview.

**Comment by scoutNinjaswapnil** [comment]
whenever I open gmeet and go inside the app again, it turn white screen ,         "react-native-webview": "^13.6.0",

**Comment by melnikovkolya** [comment]
Hi, 

I managed to establish that this was happening due to the WebView process crashing on iOS.

I found the following script that allows to imitate the termination the WebView process.


```
#/bin/bash

# Source: https://gist.github.com/jstoone/c7b5a37dedc7cd2bab3696ca387e85f0

# Find process with name containing 'launchd_sim'
SIMULATOR_PID=$(pgrep launchd_sim)
echo "Simulator PID: $SIMULATOR_PID"

# Find sub-processes for the app's WebViews
WEBKIT_CONTENT_PID=$(pgrep -P $SIMULATOR_PID 'com.apple.WebKit.WebContent')
echo "WebKit WebContent PID(s):"
echo $WEBKIT_CONTENT_PID

# Send kill signal to the selected processes.
kill $WEBKIT_CONTENT_PID
echo "WebContent processes terminated."
```

In any case, my original issue was that I had some regular expression running inside the WebView (Safari) that used the lookbehind operator, and that was not supported on iOS up to version 16.4.

**Comment by jgarplind** [comment]
> I think for Android, we should use [onRenderProcessGone](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onRenderProcessGone)
> 
> `nativeEvent.didCrash` will be false if this is just a normal technical adjustment that Android OS recycle the webview. You can reproduce this even on development, just move expo to the background, then, Genshin, start! After a while you go back, will found the warning ` WARN WebView Crashed: false`
> 
> Anyway, we can try reload the webview.
> 
> `webViewReference.current?.reload?.();` will not work.
> 
> ```ts
>   const [autoIncrementingNumber, setAutoIncrementingNumber] = useState(0);
>   return (
>     <WebView
>       key={autoIncrementingNumber}
>       onRenderProcessGone={syntheticEvent => {
>         const { nativeEvent } = syntheticEvent;
>         console.warn(
>           'WebView Crashed:',
>           nativeEvent.didCrash,
>         );
>         // webViewReference.current?.reload?.();
>         setAutoIncrementingNumber(autoIncrementingNumber + 1);
>       }}
> ```
> 
> seem to work. I don't know if this works for `nativeEvent.didCrash === true`.

Works fine also when `didCrash = true`.

Tested using `source={{ uri: autoIncrementingNumber < 5 ? "chrome://crash" : EXPO_PUBLIC_APP_URL }}` taken from [Android docs](https://developer.android.com/reference/android/webkit/WebViewClient#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)).

**Comment by mrzslr** [comment]
> fix: reload on both onRenderProcessGone onContentProcessDidTerminate

what's the aim of using key and autoIncrementingNumber instead of Webview reload?

**Comment by mrzslr** [comment]
> Most probably, we just need to use [onContentProcessDidTerminate](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#oncontentprocessdidterminate).
> 
> Related issues:
> 
> * [Webview showing blank screen #2849](https://github.com/react-native-webview/react-native-webview/issues/2849)
> * [White screen on iOS + injectJavaScript does not work in that state #2298 (comment)](https://github.com/react-native-webview/react-native-webview/issues/2298#issuecomment-1026336455)
> * [IOS WebView White Screen Issue #2302 (comment)](https://github.com/react-native-webview/react-native-webview/issues/2302#issuecomment-1566752925)
> 
> I experience the same issue with `react-native-webview@13.2.3` and `react-native@0.72.3`.
> 
> Will try to:
> 
> 1. Reload the WebView on `onContentProcessDidTerminate`
> 2. If it doesn’t work, then would wrap WebView in a React Error Boundary to log the exact error and trigger an update in a `key`, so WebView component instance would be new to see if it works w/o the necessity to clear WebView’s cache ([Webview showing blank screen #2849](https://github.com/react-native-webview/react-native-webview/issues/2849)).
> 
> ```tsx
> <ErrorBoundary> // onError, it increments autoincrementingNumber
>   <WebView key={autoincrementingNumber} />
> </ErrorBoundary>
> ```
> 
> In my case, we don’t load any 3rd party’s code, and there’s no state within the app that could go corrupted, so I’m certain the issue is on ReactNative’s side. My worry is: Webview could be silently failing outside of ReactNative and the Error Boundary wouldn’t catch the error in this case, but will report in a few days with findings.

what's the aim of using key={autoIncrementingNumber} instead of reloading the Webview?

**Comment by linonetwo** [comment]
@mrzslr 

> instead of reloading the Webview?

Due to this bug https://github.com/react-native-webview/react-native-webview/issues/3126 , I'm using 

```
source={{
            html: `<!doctype html><html lang="${
              preferredLanguage ?? 'en'
            }"><head><meta charset="UTF-8" /></head><body><div id="tidgi-mobile-webview-before-loaded-place-holder"/></body></html>`,
            /**
             * Add baseUrl to fix `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`
             * @url https://github.com/react-native-webview/react-native-webview/issues/1635#issuecomment-1021425071
             */
            baseUrl: 'http://localhost',
          }}
```

So I can't directly refresh it. I need to trigger full react component reload, so its preload script take effect and fetch content in preload script and setInnerHTML.

But I guess directly refresh it will also work, if you are using a proper uri or source.

**Comment by mrzslr** [comment]
Thank you for the answer!

**Comment by pisze-programy** [comment]
We also struggle with this issue. After the app has been active OR inactive for a while, the webview suddenly goes blank. 
```
"react-native-webview": "^13.6.4",
```

**Comment by ekko2665** [comment]
> I should have keep this issue opened.我应该一直打开这个问题。
> 
> While there is a workaround, but page reload will always cost a lot of time, make user experience not good.虽然有解决方法，但页面重新加载总是会花费大量时间，使用户体验不佳。
Is the solution for these two function do a  key refresh?：
onRenderProcessGone
onContentProcessDidTerminate

**Comment by saeid-elio** [comment]
So is this problem fixed in latest version or not? Why is the issue closed without any clear statement in this regard?

**Comment by linonetwo** [comment]
It is not fixed. We can open a new issue, and be aware not letting @github-actions close it.

**Comment by saeid-elio** [comment]
Who came up with the silly idea of automating closing of issues in this way? An issue should be closed when it's resolved or the maintainers decide they won't fix it. Either way at least one knows what he is expected to do next. I can't even understand why GitHub allowed such stupid practice in the first place.

**Comment by Nikit-Singh** [comment]
> Either way at least one knows what he is expected to do next. I can't even understand why GitHub allowed such stupid practice in the first place.

If the webview is crashed, calling the reload function won't do anything. In that case we create a new instance of the webview by changing the key

**Comment by Filk47473831** [comment]
Also struggling with this on iOS. Why is that ErrorBoundarys do not work for this prob?

**Comment by markojak** [comment]
I've been really struggling with this over a week and almost ready to say I can't use Webview because of this. Having a white screen of death just sucks 

The core of the problem lies in understanding when you need to reload the Webview vs just reloading it every time it comes to the foreground 

I found this on another issue I'm going to try at least for crashing and since we are using shareIntent I'm going to check this as wwlll


const WebViewExample = ({uri}) => {
    const webViewRef = useRef();

    // You can use uuid instead.
    // We have to change the key because sometimes it is not 
    // re-rendered in android platform after reload.
    const generateRandomKey = () => parseInt(Math.random() * 100000, 10);

    const [key, setKey] = useState(generateRandomKey());

    return (
        <WebView
            key={key}
            ref={webViewRef}
            syle={{flex: 1}}
            source={{uri: uri}}
            onLoadEnd={data => {
                const {nativeEvent} = data;
                const {title} = nativeEvent;

                if (!title.trim()) {
                    webViewRef.current?.stopLoading();
                    webViewRef.current?.reload();
                    setKey(generateRandomKey());
                }
            }}
        />
    );
};

**Comment by Tr1Fecta-7** [comment]
I managed to fix this on iOS by disabling screens from `react-native-screens`  by doing this in my `App.tsx` near top of the file:
`import { enableScreens } from 'react-native-screens';

enableScreens(false);
` 

According to their documentation, this will reduce performance.

After this, my web view would not go blank after switching tabs. I tried using `detachInactiveScreens = false` together with `lazy = false` on individual screens, but that would just make my web view refresh everytime when switching tabs.

**Comment by saeid-elio** [comment]
I couldn't find any reference to `enableScreens` in their API doc:  

https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md

**Comment by Tr1Fecta-7** [comment]
enableScreens is part of react-native-screens package, not
react-native-webview.

**Comment by Agnitsingh** [comment]
## WebView Blank Screen Issue: Problem & Solution

### Problem
#### When the app was brought back to the foreground after being in the background, the WebView would display a blank screen even though the content was loaded. This happened because Android pauses WebView rendering to save resources.

### Solution
#### Here's a a simple fix in the AppState change handler that forces the WebView to redraw its content when the app returns to the foreground:

When app becomes active again, this forces the WebView to redraw by slightly changing opacity

`

    const handleAppStateChange = (nextAppState) => {
      if (nextAppState === "active") 
      {

        if (webViewRef.current) 
        {
          webViewRef.current.injectJavaScript(`
          (function() {
            if (document.body) {
            document.body.style.opacity = 0.99;
            setTimeout(function() { document.body.style.opacity = 1; }, 3000);
          }
        
          return true;
          })();
        `);
        }
      }
      
    };

`

**Comment by saeid-elio** [comment]
For me adding the following fixed the problem and it's also less hacky:

````
onContentProcessDidTerminate={() => {
    webViewRef.current.reload();
}}
````

**Comment by zowebs** [comment]
`onContentProcessDidTerminate={() => {
    webViewRef.current.reload();
}}` is enough to solve the issue. If you wanna reproduce the behaviour, I suggest [this answer](https://stackoverflow.com/a/77745596/21601637).
