### ISSUE TITLE
Sharing session cookies on IOS does not work

### ISSUE THREAD

**Issue by jccazeaux** [react-native-webview/react-native-webview#3457]
**Bug description:**
We open a webview to login on our system. The login session is persisted with session cookies. When the webview has finished the login, we expect react native fetch to have the cookies and thus to be able to retrieve APIs.

On Android, it works great. On iOS, session cookies seem to be synced from webview to native.

**To Reproduce:**
To reproduce i have created a minimal app with a webview to Wikipedia: https://github.com/jccazeaux/rn-webview-cookies-issue

Wikipedia has a login similar to our case with session cookies (if you uncheck "Keep me logged in").

To reproduce

iOS:
```
$ npm i

# iOS:
$ npm run pods
$ npm run iOS

# Android:
$ npm run android
```

Inside the webview, **uncheck keep me logged** in and log in to your wikipedia account then press the native button "Test cookies". An alert will display the effective called url.
* If cookies are correctly used (on Android) : the effective url will be `https://en.m.wikipedia.org/wiki/Special:Notifications`
* If cookies are not sent (on iOS) : the effective url will be `https://en.m.wikipedia.org/w/index.php?returnto=Special%3ANotifications&returntoquery=&title=Special:UserLogin&warning=echo-notification-loginrequired&centralAuthAutologinTried=1&centralAuthError=Not+centrally+logged+in` (Wikipedia redirects to login page)

If you let **keep me logged** checked, wikipedia will set persistent cookies (for 1 year). Persistent cookies seem to be correctly synced.

**Expected behavior:**
On iOS and Android, alert displays 
```
URL is [${response.url} ](https://en.m.wikipedia.org/wiki/Special:Notification)
 => Connexion successful
```

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 14+
 - react-native version: 0.74
 - react-native-webview version: 13.10.2

**Comment by jccazeaux** [comment]
Hi,

I did some digging, in RNCWebViewImpl.m, [line 1832](https://github.com/react-native-webview/react-native-webview/blob/2b86b6328018666c6b06bd9c95262909d27e0555/apple/RNCWebViewImpl.m#L1832)

```
      [self syncCookiesToWebView:^{
        [wkWebViewConfig.websiteDataStore.httpCookieStore addObserver:self];
      }];
```
Completion Handler seems to never be called. Thus the observer is not set and synchronisation not done. This is due to setCookie completionHandler not called in syncCookiesToWebview function when called here. Don't know why...

I tried to add the addObserver outside the completionHandler

```
      [self syncCookiesToWebView:^{
        [wkWebViewConfig.websiteDataStore.httpCookieStore addObserver:self];
      }];
      [wkWebViewConfig.websiteDataStore.httpCookieStore addObserver:self];
```
The synchronization seems to work fine

**Comment by jccazeaux** [comment]
Any idea?

**Comment by jccazeaux** [comment]
I found something. The function `syncCookiesToWebView` is called two times
* [Line 1832](https://github.com/react-native-webview/react-native-webview/blob/2b86b6328018666c6b06bd9c95262909d27e0555/apple/RNCWebViewImpl.m#L1832) : here the `completionHandler` will add the observer to sync cookies from webview to `sharedHTTPCookieStorage`. It's broken because `completionHandler` is never called
* [Line 838](https://github.com/react-native-webview/react-native-webview/blob/2b86b6328018666c6b06bd9c95262909d27e0555/apple/RNCWebViewImpl.m#L838) : here we write cookies to webview before loading request

For obscure reasons, on the second call to `syncCookiesToWebView` the `completionHandler` is correctly called. Otherwise we wouldn't even load anything in the webview.

This behaviour seems very similar to this reported bug https://developer.apple.com/forums/thread/99674 . It has not been fixed. The described workarounds did nothing here.

But if we connect the observer for cookie changed on the second call to `syncCookiesToWebView` it fixes the bug. All works fine.

I will provide a PR with this patch

**Comment by jccazeaux** [comment]
Hi, this is a blocking issue for us. Will the PR be viewed by someone?

**Comment by killianTrm** [comment]
Same problem, fixed by this fix https://github.com/react-native-webview/react-native-webview/pull/3470

thanks !

**Comment by mathiasgmz** [comment]
Hi! The problem still persists on iOS. I've tried adding a session cookie in the request header from the new version (13.10.6) of the webview with the parameters sharedCookiesEnabled={true} and thirdPartyCookiesEnabled={true}. And it keeps returning me to the login screen. Any ideas? How can I configure the webview so that I can navigate freely with the session cookie set in the header?

**Comment by mathiasgmz** [comment]
Currently I have it like this:

const dataReq = {
uri: `https://mydomain/${currentURI}`,
headers: {
Cookie: cookie, //cookie extracted from CookieManager
}

<WebView
sharedCookiesEnabled={true}
thirdPartyCookiesEnabled={true}
source={dataReq}
/>

**Comment by jccazeaux** [comment]
This issue was for the synchronization of cookies from WebView (cookies set by web content) to native. For your case I would set the cookie in native via react-native-cookies library. It should be synchronized in webview at launch.

**Comment by saeid-elio** [comment]
I can confirm that the new release also fixed problems with cookies that I had on iOS using version 13.8.4 of WebView. Thanks @jccazeaux
