### ISSUE TITLE
`scrollEnabled=false` not work in IOS

### ISSUE THREAD

**Issue by BeaconSage** [react-native-webview/react-native-webview#3608]
**Bug description:**

`scrollEnabled=false` not work in IOS. `onScroll` still be triggered
**To Reproduce:**

The Snack code according to Expo official demo for `Webview`:
https://snack.expo.dev/@beaconsage/basic-webview-usage

**Expected behavior:**

`scrollEnabled=false`  work correctly

**Screenshots/Videos:**

https://github.com/user-attachments/assets/99f28a22-cfa5-4e5b-a8f1-1f04e3606690

**Environment:**
 - OS: IOS
 - OS version: IOS 18
 - react-native version: 0.76
 - react-native-webview version: 13.12.2

**Comment by pachun** [comment]
I am also noticing this. It's worth noting that it started happening when I upgraded from Expo SDK 51 to 52, so RN 0.74.5 to 0.76.1 in my particular case. I see @BeaconSage is also seeing it happen on RN 0.76; It might be related to the new architecture.

Also, thanks for working on this awesome component.

**Comment by bojandurmic** [comment]
Happens to me as well. It ignores the prop altogether and scrolls the webview, regardless of content or its size.

**Comment by pachun** [comment]
FWIW, I did try to clone the project and figure out what was going wrong with RN version 0.76 and I could not figure it out. The example in examples/Scrolling.tsx seems to work in 0.76. I could not reliably reproduce the problem, which isn't helpful for the package maintainers.

However, I have found that a solid workaround for me was to wrap the webview in another view with the pointerEvents prop set to "none":

```
        <View style={{ flex: 1 }} pointerEvents="none">
          <WebView
            testID={`webview-for-message-with-id-${message.id}`}
            scrollEnabled={false}
            source={{ html: Base64.decode(message.body_html) }}
            injectedJavaScript={javascriptInjectedIntoEmails}
            onMessage={(originalMessage: WebViewMessageEvent) => {
              const message = JSON.parse(originalMessage.nativeEvent.data)
              if (message.scrollHeight) {
                setHeight(message.scrollHeight)
              }
              console.debug(message)
            }}
            onShouldStartLoadWithRequest={openTappedLinksInThePhonesBrowser}
          />
        </View>
```

I am using react-native-webview 13.12.3 and that seems to work well enough for me for now.

CC @BeaconSage @bojandurmic (tagged in case you need a fix now-ish)

**Comment by bojandurmic** [comment]
Thanks @pachun ! I actually did something entirely different.

I am using Expo DOM Components (the new flashy thing that came out recently in Expo 52). They have an option not to use `react-native-webview`, but instead use their own `@expo/dom-webview`. Expo DOM Webview is on version `0.0.1` now, so it's extremely early in development, but it worked for me.

**Comment by shirakaba** [comment]
See my writeup here: https://github.com/react-native-webview/react-native-webview/issues/3555#issuecomment-2495772767. I think all props declared with `RCT_CUSTOM_VIEW_PROPERTY` may not be working when New Architecture is enabled.

**Comment by vietnutmobile** [comment]
injectedJavaScript= `  
 document.body.style.overflow = 'hidden';
  document.documentElement.style.overflow = 'hidden';
`; to fix

**Comment by Nantris** [comment]
In what environment are people seeing this? I don't see this occurring on iOS 15 on a physical device or in Simulator running 17 or 18 (I forget which.)

I didn't necessarily wire up an `onScroll` but it definitely made a difference in the behavior.

**Comment by LucasPMM** [comment]
Any updates? Same issue here

**Comment by andreialecu** [comment]
Indeed this only seems to happen on new architecture. Switched to old architecture and everything is fine.

In our case we use the [Formidable Webshell Auto-height Webview](https://formidable-webview.github.io/webshell/docs/autoheight) within scroll views. 

The problem is that if you initiate the scroll from within the webview, it bounces the webview up and down instead of scrolling the parent webview, which is a big problem.

On another hand, the new architecture has many other glitches and [performance issues](https://github.com/facebook/react-native/issues/47490) for us so we just switched back to old.

**Comment by stargt** [comment]
This is my current workaround. It works well.

```typescript
const [allowWebViewScroll, setAllowWebViewScroll] = useState(false)

useEffect(() => {
  // FIXME: temporal logic - https://github.com/react-native-webview/react-native-webview/issues/3608
  setAllowWebViewScroll(true)
  setTimeout(() => {
    setAllowWebViewScroll(false)
  }, 300)
}, [])
```

```jsx
<WebView
  scrollEnabled={allowWebViewScroll} />
```

**Comment by Nantris** [comment]
Maybe this could be integrated directly into the project, since multiple people are reporting that a delay is resolving the issue. Unless there's a more proper approach. But it should be addressed.

**Comment by Nantris** [comment]
Friendly bump. It would be really nice to not have to try workarounds for this - especially since 99% of our development takes place on Android.

**Comment by oberkayb** [comment]
i have same issue on ios 

https://github.com/user-attachments/assets/7ec31c08-eba3-4902-bce6-f438f3e4e8ec

**Comment by samu** [comment]
Solution by @stargt works for me as well. I've simplified it to this:

```
  const [scrollEnabled, setScrollEnabled] = useState(true);

  useEffect(() => {
    // Workaround for https://github.com/react-native-webview/react-native-webview/issues/3608
    setTimeout(() => setScrollEnabled(false));
  }, []);
``` 

Are there any plans of getting a proper fix for this?

**Comment by Nantris** [comment]
@Titozzz is there any chance this might be addressed? It really does degrade the look and feel on iOS when you're trying to make it feel native, and my thinking is that the presence of a workaround might shine some light on what the underlying problem is.

Unfortunately I don't have the experience on the native side to be able to debug this and submit a PR or I'd be happy to.

**Comment by Titozzz** [comment]
@Nantris , I'm on the train, I can take a look. Are you using the new arch ?

**Comment by shirakaba** [comment]
@Titozzz it does seem like a New Arch problem. See my writeup which shows some unexpected behaviour when viewed in the Xcode debugger: https://github.com/react-native-webview/react-native-webview/issues/3555#issuecomment-2495772767

**Comment by Titozzz** [comment]
So, that's pretty huge, but any boolean that had a default of true was broken: https://github.com/react-native-webview/react-native-webview/pull/3726

**Comment by shirakaba** [comment]
Can't believe you managed to ship a fix for this whilst on the train 😄 legend, thank you! 🙇

**Comment by Titozzz** [comment]
Arriving in 5 ! just in time, I've triggered the release

**Comment by Titozzz** [comment]
Fixed in 13.13.3

**Comment by samu** [comment]
@Titozzz Thank you for having a look! I tried the latest release, but unfortunately, the issue isn't fixed yet for me. Besides the `scrollEnabled` option, i also cannot get `keyboardDisplayRequiresUserAction` to work, not even with the delay hack. Any ideas what's going on?

**Comment by samu** [comment]
@Titozzz yes, i'm using the new architecture.

**Comment by samu** [comment]
@Titozzz I'm afraid i don't fully understand. I have an expo project where i deleted `node_modules` and `yarn.lock` and installed the latest `react-native-webview` version.

**Comment by verbiiyo** [comment]
hate to break it to you, but 13.13.3 did not fix it.
