### ISSUE TITLE
webview on iOS white screen

### ISSUE THREAD

**Issue by zerobox584** [react-native-webview/react-native-webview#3697]
after install react native and install package , pod install project 
and run project for show display url webview is white screen how to fix

device run project : Mac mini m2
react native : 0.77.0
react-native-webview : 13.12.2
device app : iPhone se2

```
import React, {Fragment} from 'react';
import WebView from 'react-native-webview';

export default function App() {
  return (
    <Fragment>
      <WebView
        source={{uri:'https://google.com'}}
        style={{ 
          flex: 1,
          width: '100%',
          height: '100%'
        }}
      />
    </Fragment>
  );
}

```

**Comment by dmohler20** [comment]
Ok so i had the same issue, and i could not for the life of me figure it out.  Worked perfectly fine in RN 0.76.6, when i upgraded to 0.77.0, i got a white screen.  Created a new project, and it worked, downloaded my repository it worked, re cloned my repo it did not.  Was driving me crazy, i was comparing files and pods between working and not working and what i ended up finding out was it was the length of my file path.  I moved my local repo to my home directory instead of in my documents folder structure that i had and now it works fine.  Maybe not the same issue you are having, but maybe something to check.  The worst part is there were no error messages or anything so it took me forever to figure it out.  Hope this helps.

**Comment by huxinhai** [comment]
Me, too. I'll just roll RN back to 0.76. Anyone know how to fix that?

**Comment by imthinker** [comment]
我用0.77.1版本也有这个问题，并不一定是WebView空白，也可能是父元素未设置宽高，可以尝试设置父元素的`style={{flex: 1}}`解决

**Comment by adolfogc** [comment]
I observed the same problem using RN 0.77.1 with the new architecture enabled.

**Comment by twillard22** [comment]
Disabling the new arch resolved this for me, not exactly a fix, but adding 

```ENV['RCT_NEW_ARCH_ENABLED'] = '0'```

to my pod file allowed me to build the application on the old arch where the webview is working

**Comment by kasumil** [comment]
I found the solution
I'm using

- my device: m1 max,
- "react-native": "^0.77.0"
- "react-native-webview": "^13.13.2"
- device app : iPhone 16 pro
The solution is simple: Do not wrap the WebView.

```
 // <ScrollView style={styles.container}>
    <WebView
      style={styles.webview}
      source={{uri: uri}}
      onMessage={handleOnMessage}
    />
    // </ScrollView>
```

**Comment by adolfogc** [comment]
@kasumil do you have the new architecture enabled?

**Comment by kasumil** [comment]
@adolfogc Hmm.. I’m not sure what you mean by your new architecture.

I created a new project using React Native CLI in January 2025 and proceeded with the specified version.

In my project, everything works fine as expected.

That’s why I specified that version.

**Comment by kasumil** [comment]
@husnaintahir That’s working fine…
Why did you ignore my solution?

![Image](https://github.com/user-attachments/assets/2a3e798f-fb55-4906-a5c8-cda04155a4b2)

**Comment by kasumil** [comment]
@husnaintahir Hmm… What does an old setup mean?

I have confirmed that it works properly on the iPhone SE (15.4) that I installed previously.

![Image](https://github.com/user-attachments/assets/eacc12d7-28e8-40c4-b781-7380f8e74359)

**Comment by husnaintahir** [comment]
@kasumil 

I mean that the react-native-webview works fine with the latest macOS that is **macOS Sequoia 15.31.**. It does not have to do naything with the simulator you are using, if you are using macOS Sequoia webview works fine on any simulator.

**Comment by adolfogc** [comment]
@kasumil I meant the new architecture of RN (enabled by default on 0.76+). For example, in your Podfile you can disable it by adding the following as your first line:

```
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
```

See: https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here#opt-out

**Comment by vbansal-bb** [comment]
I also facing same issue on RN version 0.77.0 on iOS, I tested on device (iPhone mini).
Note:when i switch off fabric , it works, it also works on RN v0.76.x

App.js code
**********************
import React, {Component} from 'react';
import { WebView } from 'react-native-webview';

export default class App extends Component {
 
  render() {
    return (
      <WebView
        source={{ uri: 'https://infinite.red' }}
        style={{ marginTop: 20 }}
      />
    );
  }
}
**************************
Here are the logs from xcode 
*************
nw_socket_handle_socket_event [C5:1] Socket SO_ERROR [61: Connection refused]
nw_connection_get_connected_socket_block_invoke [C5] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x303511fe0 Failed : error 0:61 [61]
nw_connection_copy_connected_local_endpoint_block_invoke [C5] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
nw_connection_copy_connected_remote_endpoint_block_invoke [C5] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
Unbalanced calls start/end for tag 20
Unbalanced calls start/end for tag 19
Running "WebViewBrowser" with {"rootTag":1,"initialProps":{},"fabric":true}
Warning: -[BETextInput attributedMarkedText] is unimplemented
nw_application_id_create_self NECP_CLIENT_ACTION_GET_SIGNED_CLIENT_ID [80: Authentication error]
Failed to resolve host network app id

*************
as any one any work around for it?

**Comment by adolfogc** [comment]
The issue remains on RN 78.0 with fabric enabled.

**Comment by aliceni81** [comment]
> I found the solution I'm using
> 
> * my device: m1 max,
> * "react-native": "^0.77.0"
> * "react-native-webview": "^13.13.2"
> * device app : iPhone 16 pro
> 
> The solution is simple: **Do not wrap the WebView.**
> 
> ```
>  // <ScrollView style={styles.container}>
>     <WebView
>       style={styles.webview}
>       source={{uri: uri}}
>       onMessage={handleOnMessage}
>     />
>     // </ScrollView>
> ```

The issue I'm experiencing is that WebView version 13.13.12 works well on iOS but not on Android.
I have to wrap the WebView component with a ScrollView and my workaround is to downgrade the react-native-webview version to 13.12.5.

**Comment by aliceni81** [comment]
> <Fragment>
>       <WebView
>         source={{uri:'https://google.com'}}
>         style={{ 
>           flex: 1,
>           width: '100%',
>           height: '100%'
>         }}
>       />
>     </Fragment>

I tested your code with new created project using react native v0.77.1 and v0.78.0 and react-native-webview v13.13.2. It does work well on both iOS and Android. But if I replace Fragment component with ScrollView, it works on iOS but not work on Android.

**Comment by aliceni81** [comment]
> the same issue is there in the newly create app with **npx @react-native-community/cli@latest init AwesomeProject**
> 
> > "dependencies": {
> > "react": "19.0.0",
> > "react-native": "0.78.0",
> > "react-native-webview": "^13.13.2"
> > },
> 
> node **20.15.0** npm **10.7.0**
> 
> here the code for App.tsx
> 
> > import React from 'react';
> > import type {PropsWithChildren} from 'react';
> > import {
> > SafeAreaView,
> > ScrollView,
> > StatusBar,
> > StyleSheet,
> > Text,
> > useColorScheme,
> > View,
> > } from 'react-native';
> > import WebView from 'react-native-webview';
> > function App(): React.JSX.Element {
> > const safePadding = '5%';
> > return (
> > <SafeAreaView
> > style={{
> > backgroundColor: '#f9f',
> > flex: 1,
> > }}>
> > <View
> > style={{
> > backgroundColor: '#ff0',
> > paddingHorizontal: safePadding,
> > paddingBottom: safePadding,
> > flex: 1,
> > }}>
> > <WebView
> > style={{lex: 1, marginTop: 0, backgroundColor: '#f00'}}
> > originWhitelist={['*']}
> > source={{
> > uri: 'https://google.com',
> > }}
> > // domStorageEnabled={true}
> > javaScriptEnabled={true}
> > messagingEnabled={true}
> > scalesPageToFit
> > javaScriptEnabledAndroid={true}
> > startInLoadingState={true}
> > onContentProcessDidTerminate={syntheticEvent => {
> > const {nativeEvent} = syntheticEvent;
> > console.warn('Content process terminated, reloading', nativeEvent);
> > }}
> > onHttpError={() => console.log('onHttpError')}
> > onLoad={() => console.log('onLoad')}
> > />
> > 
> > 
> > );
> > }
> > export default App
> 
> no errors/logs are there in the console, except a single **onLoad** log

Your code works well if <View> component is removed.

**Comment by 0anw0** [comment]
Hello, I’m encountering the same issue. after installing react-native: 0.77. and when debugging the library's native code, found that source is null, causing the WebView to open a blank page.

Video of debugging process: 

https://github.com/user-attachments/assets/641637fd-1eb1-405b-950f-715dc139633d

here's my App.tsx file: 
```
import React from 'react';
import WebView from 'react-native-webview';

function App() {
  return (
    <WebView
      enableApplePay={true}
      source={{uri: 'https://applepaydemo.apple.com/'}}
      automaticallyAdjustContentInsets={false}
      webviewDebuggingEnabled={true}
      style={{flex: 1, backgroundColor: 'blue'}}
    />
  );
}

export default App;
```

package.json
```
{
  "name": "Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.3.1",
    "react-native": "0.77.1",
    "react-native-webview": "13.13.2"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.77.1",
    "@react-native/eslint-config": "0.77.1",
    "@react-native/metro-config": "0.77.1",
    "@react-native/typescript-config": "0.77.1",
    "@types/jest": "^29.5.13",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

**Comment by 0anw0** [comment]
Thanks, @Fausto95. ```v11.23.1``` works fine on ios, but the app is crashing on android.

**Comment by Fausto95** [comment]
I've got a fork with a temporary fix: https://github.com/Fausto95/react-native-webview
It works on new arch.

**Comment by bimusiek** [comment]
@Fausto95 You made my day. The change in .ts file helped.

**Comment by vbansal-bb** [comment]
@Fausto95 Your change fixes the issue which i am able to repro on both device and all simulators on Xcode15 on react native 0.77.x.

But I noticed that issue is not occurring when using Xcode16 on same simulator and hence I am wondering how is that possible  as your change seems logical and hence wondering why  every one is not facing this issue on new architecture irrespective of react native version?

**Comment by High5Apps** [comment]
The following patch fixed things for me with react-native-webview  on 13.13.2 or 13.13.4 and react-native on 0.77.0

```diff
diff --git a/node_modules/react-native-webview/apple/RNCWebView.mm b/node_modules/react-native-webview/apple/RNCWebView.mm
index f9d080e..10d90ee 100644
--- a/node_modules/react-native-webview/apple/RNCWebView.mm
+++ b/node_modules/react-native-webview/apple/RNCWebView.mm
@@ -244,7 +244,7 @@ - (instancetype)initWithFrame:(CGRect)frame
                 webViewEventEmitter->onHttpError(data);
             }
         };
-        self.contentView = _view;
+        [self addSubview:_view];
     }
     return self;
 }
@@ -488,6 +488,12 @@ - (void)updateProps:(Props::Shared const &)props oldProps:(Props::Shared const &
     [super updateProps:props oldProps:oldProps];
 }
 
+-(void)layoutSubviews
+{
+  [super layoutSubviews];
+  _view.frame = self.bounds;
+}
+
 - (void)handleCommand:(nonnull const NSString *)commandName args:(nonnull const NSArray *)args {
     RCTRNCWebViewHandleCommand(self, commandName, args);
 }

```

**Comment by adolfogc** [comment]
I tried @Fausto95's patch, it works (using RN 0.78).

**Comment by vbansal-bb** [comment]
@Fausto95 

Thanks for sharing more information
But i still wonder 
1. what is the point for using newSource when there is already Source ?
2. Is newSource created for internal use or to be consumed  externally as well for new architecture when using WebView 
3. why it is working on 0.76 on new architecture with out your patch ? which react native changes in 0.77 introduced this issue

For Xcode 16, i can retest next week again and will come back with my findings

**Comment by Fausto95** [comment]
As end-user, you only care about `source`, `newSource` is an internal prop @vbansal-bb.

**Comment by web-iou** [comment]
@Fausto95    I'm facing the same issue , recvice `source` prop  is nil。         i want use new  arch， any solution？

**Comment by Bardiamist** [comment]
For me it was fixed in [13.13.4](https://github.com/react-native-webview/react-native-webview/releases/tag/v13.13.4)

**Comment by Amit-9081** [comment]
@Fausto95, I'm facing same issue. my RN version 0.77.0, webview version 13.13.4. 
Any solution?

**Comment by celsoantoniotendam** [comment]
I'm experiencing the same issue on RN 0.78.1 with WebView 13.13.4, macOS Sequoia 15.3.2, and an Apple M1 Pro chip.

**Comment by celsoantoniotendam** [comment]
A solution that worked for me was to install the project in a different folder, run yarn install, then navigate to the ios folder and run bundle install, followed by bundle exec pod install. This resolved the issue, likely because something was cached.

I recommend testing with a fresh installation of a WebView, making sure to set its width and height, to verify that it works correctly in a new project with the same libraries. In my case, everything is now working fine.

**Comment by kasumil** [comment]
Today, while working on a new project, I realized that in version 0.78, the output doesn’t work on Android only.
So, I downgraded to the very first feed version I had written earlier, which works on Android as well.


It only works when using 'npm i --legacy-peer-deps', but for now, 
I’ve confirmed that the output works properly on Android as well.


// package.json
`{
  "name": "RN_webview_package",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/stack": "^7.1.1",
    "react": "18.3.1",
    "react-native": "^0.77.2",
    "react-native-bootsplash": "^6.3.3",
    "react-native-gesture-handler": "^2.22.1",
    "react-native-reanimated": "^3.16.7",
    "react-native-safe-area-context": "^5.1.0",
    "react-native-screens": "^4.5.0",
    "react-native-webview": "^13.13.2"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.77.2",
    "@react-native/eslint-config": "0.77.2",
    "@react-native/metro-config": "0.77.2",
    "@react-native/typescript-config": "0.77.2",
    "@types/jest": "^29.5.13",
    "@types/react": "^19.0.0",
    "@types/react-test-renderer": "^18.0.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "reactotron-react-native": "^5.1.12",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
`

**Comment by BohBorys** [comment]
> [@High5Apps](https://github.com/High5Apps) Thanks a lot ! [Change RNCWebViewNativeComponent.ts](https://github.com/react-native-webview/react-native-webview/issues/3697#issuecomment-2697390751) works fine on iOS react-native 0.79.1 with WebView 13.13.5
> 
> The key is after change RNCWebViewNativeComponent.ts, you have to run `pod install` again, and reload your app with xcode

Same on RN 0.78.2, I am fixed with using this patch.

**Comment by dezudas** [comment]
> [@High5Apps](https://github.com/High5Apps) Thanks a lot ! [Change RNCWebViewNativeComponent.ts](https://github.com/react-native-webview/react-native-webview/issues/3697#issuecomment-2697390751) works fine on iOS react-native 0.79.1 with WebView 13.13.5
> 
> The key is after change RNCWebViewNativeComponent.ts, you have to run `pod install` again, and reload your app with xcode

thanks this works for me too 0.78.2 better to have this update as a release

**Comment by johndpope** [comment]
@dmohler20 "I moved my local repo to my home directory instead of in my documents folder structure that i had and now it works fine". - bizarrely this fixed it for me for ios - react native 79 / expo 53 / pnpm / node 20.19 / m1

**Comment by Titozzz** [comment]
1) Addressed by 13.14.1
2) Addressed by https://github.com/facebook/react-native/commit/91d034533e9f52232b351bb88b2ae7b48704e68f (already fixed in 0.80)

**Comment by steavenb** [comment]
@Titozzz Thanks for sending out a fix.

Unfortunately, even after updating to the latest, I still have this issue.

Not sure if it is related, but some devices get stuck with a white screen at the opening of the app (right after splash screen) and some get the white screen on the webview.

Also, this error does not occur when I build the apps using my Intel-based Mac (even with older versions of the webview package)

**Comment by delphinebugner** [comment]
Thanks for the fix @Titozzz , upgraded to Webview 13.14.1 and I don't have the issue anymore 🙂

**Comment by joaonew** [comment]
here fixed as well, thank you and god job!

**Comment by warz-ar** [comment]
> I found the solution I'm using
> 
> * my device: m1 max,
> * "react-native": "^0.77.0"
> * "react-native-webview": "^13.13.2"
> * device app : iPhone 16 pro
> 
> The solution is simple: **Do not wrap the WebView.**
> 
> ```
>  // <ScrollView style={styles.container}>
>     <WebView
>       style={styles.webview}
>       source={{uri: uri}}
>       onMessage={handleOnMessage}
>     />
>     // </ScrollView>
> ```

you are right bro. when i set "react-native-webview": "^13.13.2". it work.

my RN is 0.80.0, device app same with you.

**Comment by margotbignon** [comment]
I have this problem with RN 77 new arch react-native-webview 13.14.1. I tried with 13.12.5, 13.16.0... Do you know what can I do ?

**Comment by Ruchita-uninow** [comment]
i have "react-native": "0.77.3" and "react-native-webview": "13.16.0", still not working for my side in above version ios 17.0  simulators
